name: Updating functions.py
on:
  schedule:
    - cron: "0 0 * * *" # run at the start of every day
  workflow_dispatch:

jobs:
  update-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3

      - name: Cloning Apacelus/python-os-functions repo
        run: git clone https://github.com/Apacelus/python-os-functions

      - name: Updating functions.py
        run: cp ./python-os-functions/functions.py ./functions.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Update functions.py

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: 'functions.py'